baseURL = 'https://erengokirmak.com/'
languageCode = 'en-us'
title = 'Şükrü Eren Gökırmak'
theme = 'PaperMod'
copyright = "şükrü eren gökırmak · [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"
outputs = { home = ["HTML", "JSON"] }

[taxonomies]
tag = "tags"
category = "categories"

[minify]
disableXML = true
minifyOutput = true

[params]
description = 'Personal blog of Şükrü Eren Gökırmak'
author = 'Şükrü Eren Gökırmak'
homeInfoParams = { title = 'welcome!', content = 'I write and code and everything in-between. this is where to find them.'}
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowRssButtonInSectionTermList = true

[params.profileMode]
enabled = true
subtitle = "I write and code and everything in-between. this is where to find them."
[[params.profileMode.buttons]]
name = "Posts"
url = "/posts/"

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/erengokirmak'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://linkedin.com/in/sukruerengokirmak'

[[params.socialIcons]]
name = 'orcid'
url = 'https://orcid.org/0009-0003-2128-7872'

[[params.socialIcons]]
name = 'email'
url = 'mailto:sukruerengokirmak@gmail.com'

[[params.socialIcons]]
name = 'cv'
url = '/Sukru_Eren_Gokirmak_CV.pdf'


[[menu.main]]
name = 'Tags'
url = '/tags/'
weight = 20

[[menu.main]]
name = 'Archives'
url = '/archives/'
weight = 30

[[menu.main]]
name = 'Search'
url = '/search/'
weight = 40
